# Generated by Django 3.2 on 2023-10-04 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название урока')),
                ('video_link', models.URLField(verbose_name='Ссылка на видеоурок')),
                ('duration', models.DurationField(default=0, verbose_name='Длительность видео')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя продукта')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to=settings.AUTH_USER_MODEL, verbose_name='Автор продукта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProductLessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons_amount', to='product.lesson', verbose_name='Урок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons_amount', to='product.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name_plural': 'Количество уроков в продукте',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='lesson',
            field=models.ManyToManyField(through='product.ProductLessons', to='product.Lesson', verbose_name='Уроки продукта'),
        ),
        migrations.CreateModel(
            name='LessonStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField(default=0)),
                ('last_time_watched', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat', to='product.lesson', verbose_name='Урок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Статус уроков',
            },
        ),
        migrations.AddConstraint(
            model_name='productlessons',
            constraint=models.UniqueConstraint(fields=('product', 'lessons'), name='unique_ingredient'),
        ),
    ]
