# Generated by Django 3.2 on 2023-10-03 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to=settings.AUTH_USER_MODEL, verbose_name='Автор продукта'),
        ),
        migrations.AddField(
            model_name='product',
            name='lesson',
            field=models.ManyToManyField(through='product.ProductLessons', to='product.Lesson', verbose_name='Уроки продукта'),
        ),
        migrations.AddField(
            model_name='lessonstatus',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat', to='product.lesson', verbose_name='Урок'),
        ),
        migrations.AddField(
            model_name='lessonstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddConstraint(
            model_name='productlessons',
            constraint=models.UniqueConstraint(fields=('product', 'lessons'), name='unique_ingredient'),
        ),
    ]
