# Generated by Django 3.2 on 2023-10-04 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Длительность видео'),
        ),
    ]
